import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import AuthProvider from "@/components/AuthProvider";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import { GlobalProvider } from "@/context/GlobalContext";


export const metadata = {
  title: "Property Pulse",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <GlobalProvider>
    <html lang="en">
      <head>
      </head>
      <body className="bg-white text-white">
          <Navbar />
          <main>{children}</main>
          <Footer />
          <ToastContainer />
      </body>
    </html>
    </GlobalProvider>
    </AuthProvider>
  );
}
