import "./globals.css";
import Navbar from "@/components/Navbar";


export const metadata = {
  title: "Property Pulse",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="http://localhost:8097"></script>
      </head>
      <body
       className="bg-white text-white">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
